SELECT * FROM my_table
SELECT * FROM BE_cible
select ENTITE;
truncate table my_table;



Insert into MY_TABLE (VAL_DATE,VERSION,CLOSING_TYPE,ENTITY,ACCIDENT_UNDERWRITING_YEAR,REVIEW_SEGMENT,MPSO,OPERATION_TYPE,INTERCOMPANY,ACCOUNT_TYPE,DEVELOPMENT_YEAR,VALUE_TOTAL,CURRENCY,TARGETTABLE,VARFLEX) values ('01/01/2025',null,null,null,null,null,null,'1',null,null,null,null,null,'BE',null);
Insert into MY_TABLE (VAL_DATE,VERSION,CLOSING_TYPE,ENTITY,ACCIDENT_UNDERWRITING_YEAR,REVIEW_SEGMENT,MPSO,OPERATION_TYPE,INTERCOMPANY,ACCOUNT_TYPE,DEVELOPMENT_YEAR,VALUE_TOTAL,CURRENCY,TARGETTABLE,VARFLEX) values ('01/01/2026',null,null,null,null,null,null,'2',null,null,null,null,null,'BE',null);
Insert into MY_TABLE (VAL_DATE,VERSION,CLOSING_TYPE,ENTITY,ACCIDENT_UNDERWRITING_YEAR,REVIEW_SEGMENT,MPSO,OPERATION_TYPE,INTERCOMPANY,ACCOUNT_TYPE,DEVELOPMENT_YEAR,VALUE_TOTAL,CURRENCY,TARGETTABLE,VARFLEX) values ('01/01/2025',null,null,null,null,null,null,'1',null,null,null,null,null,'BE',null);
Insert into MY_TABLE (VAL_DATE,VERSION,CLOSING_TYPE,ENTITY,ACCIDENT_UNDERWRITING_YEAR,REVIEW_SEGMENT,MPSO,OPERATION_TYPE,INTERCOMPANY,ACCOUNT_TYPE,DEVELOPMENT_YEAR,VALUE_TOTAL,CURRENCY,TARGETTABLE,VARFLEX) values ('01/01/2026',null,null,null,null,null,null,'2',null,null,null,null,null,'BE',null);
Insert into MY_TABLE (VAL_DATE,VERSION,CLOSING_TYPE,ENTITY,ACCIDENT_UNDERWRITING_YEAR,REVIEW_SEGMENT,MPSO,OPERATION_TYPE,INTERCOMPANY,ACCOUNT_TYPE,DEVELOPMENT_YEAR,VALUE_TOTAL,CURRENCY,TARGETTABLE,VARFLEX) values ('01/01/2027',null,null,null,null,null,null,'2',null,null,null,null,null,'B',null);

-----création table source
CREATE TABLE my_table (
    VAL_DATE VARCHAR2(10),
    VERSION NUMBER(20),
    CLOSING_TYPE VARCHAR2(20),
    ENTITY VARCHAR2(20),
   ACCIDENT_UNDERWRITING_YEAR NUMBER(4),
    REVIEW_SEGMENT VARCHAR2(255),
    MPSO NUMBER(20),
    OPERATION_TYPE VARCHAR2(20),
    INTERCOMPANY VARCHAR2(40),
    ACCOUNT_TYPE NUMBER(4),
    DEVELOPMENT_YEAR NUMBER(4),
    VALUE_TOTAL NUMBER(20, 10),
    CURRENCY VARCHAR2(5),
    TARGETTABLE VARCHAR2(64),
    VARFLEX varchar(64)
);
-------création table cible
CREATE TABLE BE_CIBLE (
    KEY_DATE               VARCHAR2(10),
    ACTUARIAL_PORTFOLIO    VARCHAR2(40),
    COST_REVENUE_ELEMENT   VARCHAR2(10),
    LEGAL_ENTITY           VARCHAR2(10),
    SETTLED_DATE           VARCHAR2(8),
    ISSUE_DATE             VARCHAR2(8),
    INFORCE_NEW_BUSINESS   VARCHAR2(5),
    EXPECTATION_CHANGE     VARCHAR2(2),
    CHANGE_REASON          NUMBER(6),
    TRANCHE_START_DATE     VARCHAR2(8),
    INCURRED_DATE          VARCHAR2(8),
    REPORTED_DATE          VARCHAR2(8),
    DUE_DATE               VARCHAR2(8),
    INTERCOS               VARCHAR2(5),
    EXPECTED_PAY_CRY       VARCHAR2(5),
    EXPECTED_PAY_AMOUNT    NUMBER(20,10),
    COVERAGE_CRY           VARCHAR2(5),
    COVERAGE_AMOUNT        NUMBER(20,10),
    ITEM_ID                NUMBER(6),
    DELIVERY_PACKAGE       VARCHAR2(20)
);

INSERT INTO my_table (val_date) VALUES (TO_DATE('01/01/2025', 'DD/MM/YYYY'));
INSERT INTO my_table (val_date) VALUES (TO_DATE('01/01/2026', 'DD/MM/YYYY'));

COMMIT;

INSERT INTO MY_TABLE
(VAL_DATE, VERSION, CLOSING_TYPE, ENTITY, ACCIDENT_UNDERWRITING_YEAR, REVIEW_SEGMENT, MPSO, OPERATION_TYPE, INTERCOMPANY, ACCOUNT_TYPE, DEVELOPMENT_YEAR, VALUE_TOTAL, CURRENCY, TARGETTABLE, VARFLEX)
VALUES
(TO_DATE('01/01/2025', 'DD/MM/YYYY'), NULL, NULL, 'GRAA', NULL, NULL, NULL, '1', NULL, NULL, '2026', NULL, NULL, 'BE', NULL);

INSERT INTO MY_TABLE
(VAL_DATE, VERSION, CLOSING_TYPE, ENTITY, ACCIDENT_UNDERWRITING_YEAR, REVIEW_SEGMENT, MPSO, OPERATION_TYPE, INTERCOMPANY, ACCOUNT_TYPE, DEVELOPMENT_YEAR, VALUE_TOTAL, CURRENCY, TARGETTABLE, VARFLEX)
VALUES
(TO_DATE('01/01/2026', 'DD/MM/YYYY'), NULL, NULL, 'GRAA', NULL, NULL, NULL, '2', NULL, NULL, '2026', NULL, NULL, 'BE', NULL);

INSERT INTO MY_TABLE
(VAL_DATE, VERSION, CLOSING_TYPE, ENTITY, ACCIDENT_UNDERWRITING_YEAR, REVIEW_SEGMENT, MPSO, OPERATION_TYPE, INTERCOMPANY, ACCOUNT_TYPE, DEVELOPMENT_YEAR, VALUE_TOTAL, CURRENCY, TARGETTABLE, VARFLEX)
VALUES
(TO_DATE('01/01/2025', 'DD/MM/YYYY'), NULL, NULL, 'GR33', NULL, NULL, NULL, '1', NULL, NULL, '2026', NULL, NULL, 'BE', NULL);

INSERT INTO MY_TABLE
(VAL_DATE, VERSION, CLOSING_TYPE, ENTITY, ACCIDENT_UNDERWRITING_YEAR, REVIEW_SEGMENT, MPSO, OPERATION_TYPE, INTERCOMPANY, ACCOUNT_TYPE, DEVELOPMENT_YEAR, VALUE_TOTAL, CURRENCY, TARGETTABLE, VARFLEX)
VALUES
(TO_DATE('01/01/2026', 'DD/MM/YYYY'), NULL, NULL, 'GR33', NULL, NULL, NULL, '2', NULL, NULL, '2026', NULL, NULL, 'BE', NULL);

INSERT INTO MY_TABLE
(VAL_DATE, VERSION, CLOSING_TYPE, ENTITY, ACCIDENT_UNDERWRITING_YEAR, REVIEW_SEGMENT, MPSO, OPERATION_TYPE, INTERCOMPANY, ACCOUNT_TYPE, DEVELOPMENT_YEAR, VALUE_TOTAL, CURRENCY, TARGETTABLE, VARFLEX)
VALUES
(TO_DATE('01/01/2027', 'DD/MM/YYYY'), NULL, NULL, NULL, NULL, NULL, NULL, '2', NULL, NULL, NULL, NULL, NULL, 'B', NULL);

CREATE TABLE ENTITE
(
  LEGAL_ENTITY VARCHAR2(8 BYTE),
  ENTITE VARCHAR2(8 BYTE),
  DATTE VARCHAR2(8 BYTE)
);

SELECT * FROM ENTITE;

Insert into ENTITE (LEGAL_ENTITY,ENTITE,DATTE) values ('CR69','GRAA','20230101');
Insert into ENTITE (LEGAL_ENTITY,ENTITE,DATTE) values ('CR10','GR33','20260101');




